---
- name: Ensure Nginx and required modules are installed
  yum:
    name:
      - 'nginx'
      - 'nginx-mod-stream'
    # state: present, in order not to upgrade any package to an untested version
    state: present
  become: yes
  tags: nginx-service

- name: Ensure Nginx is started
  service:
    name: 'nginx'
    state: 'started'
    enabled: 'yes'
  become: yes
  tags: nginx-service
