---
- name: Ensure Nginx is installed
  yum:
    name: 'nginx'
    state: 'latest'
  become: yes
  tags: nginx-service

- name: Ensure Nginx is started
  service:
    name: 'nginx'
    state: 'started'
    enabled: 'yes'
  become: yes
  tags: nginx-service
